-- DIRECTOR
INSERT INTO director (first_name, last_name)
VALUES
('chuck', 'jones'),
('ben', 'washam'),
('bill', 'melendez'),
('bob', 'clark'),
('richard', 'donner'),
('jules', 'bass'),
('arthur', 'rankin jr'),
('troy', 'miller'),
('larry', 'roemer'),
('george', 'seaton'),
('nancy', 'meyers'),
('henry', 'selick'),
('brian', 'levant'),
('chris', 'columbus'),
('jack', 'smight'),
('john', 'pasquin'),
('jon', 'favreau'),
('brady', 'connell'),
('steve', 'hryniewicz'),
('mike', 'bickerton'),
('nicholas', 'berry'),
('jeanette', 'goulbourn'),
('robert', 'zemeckis'),
('richard', 'schenkman'),
('malcolm', 'd lee'),
('jon', 'favreau');

-- PRODUCER
INSERT INTO producer (producer) (first_name, last_name)
VALUES
('dr.', 'seuss'),
('chuck', 'jones'),
('lee', 'mendelson'),
('bill', 'melendez'),
('bob', 'clark'),
('gary', 'goth'),
('rene', 'dupont'),
('richard', 'donner'),
('art', 'linson'),
('jules', 'bass'),
('arthur', 'rankin jr'),
('irving', 'azoff'),
('william', 'perlberg'),
('nancy', 'meyers'),
('bruce', 'a block'),
('tim', 'burton'),
('denise', 'di novi'),
('chris', 'columbus'),
('michael', 'barnathan'),
('mark', 'radcliffe'),
('buck houghton'),
('robert', 'zemeckis'),
('richard', 'schenkman'),
('brady', 'connell'),
('malcolm', 'd lee'),
('jon', 'favreau');